### ISSUE TITLE
code and CLIP model weight

### ISSUE THREAD

**Issue by dialogueeeeee** [songrise/CLIP-Count#1]
Thanks for the interesting insights!

Will you be releasing the code and CLIP model weight soon? Thanks in advance!

**Comment by songrise** [comment]
Thanks, I will release the code after receiving review opinion. For the "CLIP model weight", if you are asking for the weight for CLIP encoders, we use the OpenAI CLIP ViT-B/16 without fine-tuning. If you mean the weight for our trainable part, I will consider releasing them along with the code.

**Comment by songrise** [comment]
> Thanks, I will release the code after receiving review opinion. For the "CLIP model weight", if you are asking for the weight for CLIP encoders, we use the OpenAI CLIP ViT-B/16 without fine-tuning. If you mean the weight for our trainable part, I will consider releasing them along with the code.

Our paper has been accepted by ACM MM 2023, I will release the code and model weight around August.

**Comment by songrise** [comment]
The code has been released
