### ISSUE TITLE
Weights Access Denied 

### ISSUE THREAD

**Issue by lachhabw** [songrise/CLIP-Count#2]
Hello there! Thank you for sharing this repository.
I encountered an issue while trying to download the weights from Google Drive, as it requires access permissions.
Is there an alternative way to access or download the weights? Your assistance would be greatly appreciated. Thank you!

**Comment by songrise** [comment]
hi, I forgot to set the access permission. please try this link https://drive.google.com/file/d/17Dj0tjd29lPGOGYEF5IrE8aPClXUjTrR/view?usp=sharing.
